### PR TITLE
Fixing Issue with $constant beeing of type /Cake/ORM/Entity

### LINKED ISSUE #55: Error in ConstStrategy while formatig results
I get the following error when I use the const strategy with enum:

`Cake\Utility\Hash::get(): Argument #2 ($path) must be of type array|string|int|null, Cake\ORM\Entity given, called in /application/vendor/cakedc/enum/src/Model/Behavior/Strategy/ConstStrategy.php on line 133`

The situation i experience is that while iterating through the result set of a query the $row in the beforeFind event already has been formated and is of type Cake\ORM\Entity.

I do not understand how this happens, but it can be fixed by adding the line

`if ($constant instanceof Entity) return $row;` after line 128 in the class ConstStrategy.

### PR DESCRIPTION
**Pull request by kaihoefler**
fixes #55

### CODE REVIEW

**Review by arusinowski — APPROVED** [review]

File: src/Model/Behavior/Strategy/ConstStrategy.php [hunk 1]
```diff
@@ -132,6 +132,8 @@ public function beforeFind(EventInterface $event, Query $query, ArrayObject $opt
 
                 $constant = Hash::get($row, $this->getConfig('field'));
 
+                if ($constant instanceof Entity) return $row;
```
Comment (skie) [inline src/Model/Behavior/Strategy/ConstStrategy.php]: "If" without curly brackets break cakephp style guide.

Comment (kaihoefler) [reply src/Model/Behavior/Strategy/ConstStrategy.php]: FIxed it
